# -*- coding: utf-8 -*-
"""Assignment_5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uz9KU4g_9ADe6sT96teDl2r3nMaEHxhu

**Task 1: Create a Dictionary of Student Marks**
"""

dict={'Harsh':89,'Aryan':98,'Sanjay':99}

a = input("Enter the name of the student: ")
if a in dict:
  print(a+"'s Marks:",dict[a])
else:
  print("Student not found")

"""**Task 2: Demonstrate List Slicing**"""

list = [1,2,3,4,5,6,7,8,9,10]
print("Original list:",list)
a=list[0:5]
print("Extracted first five elemelements:",a)
a.reverse()
print("Reversed extracted list:",a)